import React from 'react';
import { type NextPage } from 'next';
import Head from 'next/head';
import RegisterForm from '../components/authentication/RegisterForm';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <style>{`
          body {
            background-image: url('/bg.jpeg');
            background-repeat: no-repeat;
            background-size: cover;
          }
        `}</style>
        <title>Notes App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='container-fluid text-center mt-4'>
        <h1 className='fw-500 h1 text-white'>Notes App</h1>
        <RegisterForm />
      </div>
    </>
  );
};

export default Home;
